### ISSUE TITLE
Support Red Alloy Wire form Project Red

### ISSUE THREAD

**Issue by miuirussia** [UnwrittenFun/ImmersiveIntegration#12]
Project red wires not connecting to wire connector

**Comment by marcin212** [comment]
and RedLogic

**Comment by jamesbirtles** [comment]
Project red support is done, Blue power and Red logic are todo.

**Comment by jamesbirtles** [comment]
Original suggestion was implemented so closing this issue. If anyone wants support for others, open a new issue.
