### ISSUE TITLE
Config doesn't get new entries

### ISSUE THREAD

**Issue by CaitlynMainer** [UnwrittenFun/ImmersiveIntegration#13]
Updated to the latest release, and my config was overwritten with default values, and does not have the entry for redstoneWireRange

**Comment by jamesbirtles** [comment]
could you paste in your current config file?

**Comment by CaitlynMainer** [comment]
# Configuration file

```
general {
    # The maximum range of Dense Wires before needing a support [range: 1 ~ 64, default: 8]
    I:denseWireRange=8

    # Enable/disable the AE2 specific content if AE2 is installed [default: true]
    B:enableAE=true

    # The maximum range of Fluix Wires before needing a support [range: 1 ~ 64, default: 16]
    I:fluixWireRange=16
}


options {
    I:denseWireRange=64
    I:fluixWireRange=64
}
```

**Comment by CaitlynMainer** [comment]
Manually adding the redstoneWireRange to the config worked, so I just did that for now.

**Comment by jamesbirtles** [comment]
So the reason for the override is the category changed to general, not sure why redstoneWireRange didn't generate

**Comment by jamesbirtles** [comment]
If I remove that config option manually, it gets added back when I launch so I can't reproduce this

**Comment by CaitlynMainer** [comment]
Sorry, I got super busy.. I just deleted the config, and started the client, the config is missing the " redstoneWireRange " entry.

http://paste.pc-logix.com/view/5e9ee8ab

**Comment by jamesbirtles** [comment]
I just realised I forgot to add redstoneWireRange to 0.4.0, that is why it is generating on mine but not yours, will be in the next version :)

**Comment by CaitlynMainer** [comment]
Well, atleast adding the entry manually works, so there's that.  Thanks!
