### ISSUE TITLE
Crashing without projectred

### ISSUE THREAD

**Issue by primetoxinz** [UnwrittenFun/ImmersiveIntegration#14]
projectred wasn't made a dependency but is required none the less. (I don't want to get it)

**Comment by jamesbirtles** [comment]
It shouldn't be required and I thought it wasn't must of missed something I am checking now

**Comment by jamesbirtles** [comment]
I just tried out using just IE v0.4.4 and II v0.4.1 and have not experienced a crash. Do you have the crash log?

**Comment by primetoxinz** [comment]
I can't reproduce it again, I don't know what was happening with it.
