### ISSUE TITLE
ME Wire Connectors adding on chunk load

### ISSUE THREAD

**Issue by wolfcomp** [UnwrittenFun/ImmersiveIntegration#17]
So me and alfw have tested this issue, and if you have ME Wire Connectors and unload a chunk and load it again you get more than you have, and the ME system crashes on it self. Why unwritten why :(

**Comment by jamesbirtles** [comment]
what do you mean by get more than you have?

**Comment by wolfcomp** [comment]
i have 6 when i unload it and load it again i have 11 on the me network but still only 6 in the world
