### ISSUE TITLE
Set robin needs shiftright click 

### ISSUE THREAD

**Issue by bakaxyf** [UnwrittenFun/ImmersiveIntegration#19]
To avoiding mis-clicking :p

**Comment by jamesbirtles** [comment]
Trouble with that is then shift right clicking with a block stack wouldn't work

**Comment by jamesbirtles** [comment]
Perhaps a shift right click only to set it to 0?

**Comment by CannonFotter** [comment]
I think shift-right click the robin to lock it when using the engineer‘s hammer may be better

**Comment by jamesbirtles** [comment]
That could work
