### ISSUE TITLE
Wooden posts ext. act as the wooden posts. (Ladderification)

### ISSUE THREAD

**Issue by jena-s-lab** [UnwrittenFun/ImmersiveIntegration#21]
Hello,
A simple feature request:
The IE wooden posts act as ladders.
Please, make the extension act the same.

Versions:
Forge 1.7.10-10.13.4.1492
AE2 rv2 stable 10
IE 0.5.2
II 0.4.2

**Comment by bakaxyf** [comment]
#9

**Comment by jena-s-lab** [comment]
ok :neutral_face: 

Thank you anyway that's a neat mod ! :)
