### ISSUE TITLE
Crash caused by break redstone connector

### ISSUE THREAD

**Issue by karakufire** [UnwrittenFun/ImmersiveIntegration#22]
following bug report.
http://pastebin.com/NbJgmS7e
Situation: break wooden post(IE), and wire connected redstone wire connector in chain.

**Comment by jamesbirtles** [comment]
I cannot reproduce this?

**Comment by karakufire** [comment]
Here's image.
http://i.imgur.com/hi83p57.png
When break wooden post, ConcurrentModificationException is caused.

**Comment by jamesbirtles** [comment]
Well that was a pain in the butt to find
