### ISSUE TITLE
[0.4.2] Hitting dense connector with a IE hammer destroys the block

### ISSUE THREAD

**Issue by xenoflot** [UnwrittenFun/ImmersiveIntegration#23]
Hi guys, I'm running ver 0.4.2 and I've found that hitting a dense ME connector with a IE hammer destroys the block instantly as if I were in creative mode.

Oh and you really missed an opportunity by not calling the mod Immersive Energistics :-)

Love the mod, thanks!

**Comment by jamesbirtles** [comment]
Immersive Energistics would mean I couldn't add non-ae stuff :P. And i'll look into it

**Comment by xenoflot** [comment]
Turns out that tapping with an empty hand has the same effect. Linked wires are returned but not the connector.

edit: removing extra comments to a separate issue

**Comment by jamesbirtles** [comment]
I believe some mod adds the ability to instantly break blocks you have recently placed. This might be what is causing this as I cannot reproduce this.
