### ISSUE TITLE
[0.4.2] ME connection lost with chunk unload

### ISSUE THREAD

**Issue by xenoflot** [UnwrittenFun/ImmersiveIntegration#24]
I made a run of dense ME wire between two buildings. It worked fine but following server reboot, there's no communication down the lines. I broke all the posts, recovered the bits and re-ran the lines and it's fine again.

I later made a run with regular ME wire (not dense) to another place. Working fine but when I wandered away (via nether to another player's home), when I returned it had lost connection. Assuming it's chunk unload related.

If you can direct me for further testing, I'm happy to help.

edit: possibly relevant. Server admin said his log is being spammed by this: http://pastebin.com/AmhTzPWd

**Comment by jamesbirtles** [comment]
I'm reworking the way me wires work so I'm going to close this for now.. reopen if still an issue in the next update.
