### ISSUE TITLE
Redstone Transformer

### ISSUE THREAD

**Issue by elfifae** [UnwrittenFun/ImmersiveIntegration#29]
Instead of ProjectRed's bundled cables connecting directly to a redstone wire connector, what if a transformer was available that acted as a sort of unifying bus, allowing connections directly to both ProjectRed and similar wires, MFR's rednet cables, and even exposing a redstone component interface for OpenComputers?

Alternatively, maybe II and ZI could work together to make a redstone wire connector with an inbuilt OC component interface/support for the tier 2 redstone card? I dunno.

**Comment by magik6k** [comment]
God no, having transformer here makes absolutely no logical sense, same goes to ME transformers, they make no sense, there wasn't even any warning that things may break(ME transformer broke my whole huuuuudge ME network)

**Comment by jamesbirtles** [comment]
Mod is pre v1, things may break.

**Comment by magik6k** [comment]
This still doesn't change the fact that transformers doesn't make any sense here/for that use. The power transformers for power lines convert max RF/t(sort of voltage), and all connectors are still perfectly able to connect to any RF device. Only thing ME transformers do now is convert from/to other network devices, it make no sense here. If ME transformer was used to convert form dense to non-dense I'd be really happy with it.

Same goes to Redstone transformers. In case we had a transformer that could be colored to insert single redstone lines into bundled cables it'd make sense.

**Comment by jamesbirtles** [comment]
ME transformer converts from a parallel signal from the me cable, to a serial signal to go over the single wire. And then back again. Makes perfect sense to me

**Comment by elfifae** [comment]
Magik, if you didn't want things to break, you shouldn't have fed Da Huuuuuudge.
