### ISSUE TITLE
weird crash -> java.lang.ArrayIndexOutOfBoundsException: 5

### ISSUE THREAD

**Issue by Sailren** [UnwrittenFun/ImmersiveIntegration#32]
looks like your industrial coke oven has a problem with vanilla hoppers, see here: http://paste.ubuntu.com/12295725/

the hoppers are all connected to the coke oven, i placed 8 hoppers around the oven with the output face to the oven

**Comment by Sailren** [comment]
i think the oven tries to autooutput to the hoppers but he cant cuz all hoppers are full of coal, supplied by creative strongboxes from TE

**Comment by jamesbirtles** [comment]
Build with the fix: http://minecraft.curseforge.com/mc-mods/232159-immersive-integration/files/2255878
