### ISSUE TITLE
0.5.4 cannot be cast to

### ISSUE THREAD

**Issue by SvEgiiVEteR** [UnwrittenFun/ImmersiveIntegration#33]
crash the server world
http://pastebin.com/vzdv33eB

**Comment by jamesbirtles** [comment]
I don't think the is my issue, why would ender io be trying to cast my connector to there shit..  report it to ender io and see what they say

**Comment by SvEgiiVEteR** [comment]
Yes, I think you are correct a problem of a different kind.
the server does not show the entire log.
You can close the issues
problem indirectly related to RFTools

**Comment by jamesbirtles** [comment]
Okay hope you can get it sorted
