### ISSUE TITLE
ComputerCraft networking cables

### ISSUE THREAD

**Issue by ChanceNCounter** [UnwrittenFun/ImmersiveIntegration#38]
I'm sure this has been mentioned somewhere, but I can't find it, so I thought I'd submit a feature request.

I like the notion of CC cabling hanging up there with the rest of the good stuff. Plus, IE + ImmersiveIntegration has pretty much freed me from the need to run long cable trenches under a large base, except for this one thing. I don't know if it's feasible, but I'd be enormously grateful if you took a look.

**Comment by jamesbirtles** [comment]
Having looked into it this doesn't seem possible (at least without a tonne of work) right now. Will reopen if anything changes in that regard.
