### ISSUE TITLE
Me transformer duplication bug on servers

### ISSUE THREAD

**Issue by zed-hex** [UnwrittenFun/ImmersiveIntegration#39]
If someone places a me transformer so the base of it contacts a duct from thermal dynamics (duct need power) or a cell from the same mod (outputting power on the top face) when on a server will give the player an internal server error. When the player reconnects to the server they still have the transformer in there hand and it is also placed in the world. I have tested with extra utilities, buildcraft and also immersive engineering power systems and I could not replicated the problem 
Mods that could be relevant to the bug:
Immersive integration 0.5.4
Immersive engineering 0.5.4
Thermal dynamics 1.1.0-161
Cofh core 3.0.3- 303
Ae2 rv2 stable 10

**Comment by jamesbirtles** [comment]
I can't reproduce this

**Comment by zed-hex** [comment]
I have just re tried replicating it and I can’t get it to happen anymore (I have updated lot of mods from when I last tested this). So my guess it was some other mod conflicting in some strange way but it looks like it is fixed now so I will close this.

**Comment by jamesbirtles** [comment]
Awesome :)
