### ISSUE TITLE
ME transformer taking insane amounts of power

### ISSUE THREAD

**Issue by BBoldt** [UnwrittenFun/ImmersiveIntegration#40]
Not sure if this is intended or not, but it seems to take so much power that it is cheaper just to use regular ME cables and not even touch the ME wires.

For instance, I have this setup: 
![](http://i.imgur.com/jiHKpzs.png)
That is two transformers, 35 blocks apart, connected with regular non-dense ME wires.

Without the transformers connected, my small ME network takes 21rf/t.
![](http://i.imgur.com/6I1zFtR.png)
![](http://i.imgur.com/BvZQwwX.png)

With the transformers connected, the ME network takes 90rf/t.
![](http://i.imgur.com/vFpXhL7.png)

So, just for those two transformers, I need an extra 70rf/t. It just seems really excessive to me and makes me not want to use the wires at all.

**Comment by jamesbirtles** [comment]
Me wires aren't designed to replace regular ae cables. They are designed for medium to long distance transmission where running a tonne of cable would be a pain and you are willing to sacrifice power to avoid using cable.

**Comment by BBoldt** [comment]
okay
