### ISSUE TITLE
[Minetweaker Support]: Minetweaker Support for the Industrial Coke Oven

### ISSUE THREAD

**Issue by Lanse505** [UnwrittenFun/ImmersiveIntegration#43]
This is just a small suggestion as the base Coke Oven from IE has MT Support why not the Industrial Size one also <3 :3

**Comment by OneEyeMaker** [comment]
If you add recipe to Coke Oven from IE, it automatically adds to Industrial Coke Oven. Why do you need another (separated) MT handler for that?

**Comment by Lanse505** [comment]
I did not know this since I couldn't find any documentation pointing towards that fact. Thanks for informing me ^^
