### ISSUE TITLE
Crash with Immersive Engineering 0.6.0

### ISSUE THREAD

**Issue by BBoldt** [UnwrittenFun/ImmersiveIntegration#44]
https://gist.github.com/d29e99f337c4cfd42f0f
- ImmersiveEngineering-0.6.0
- Forge 1492

Full modlist: https://gist.github.com/f56db34443ab577a121d

https://github.com/BluSunrize/ImmersiveEngineering/issues/555

**Comment by jamesbirtles** [comment]
Yeah it isn't gonna work with 0.6.0 until I update all my code

**Comment by BBoldt** [comment]
No big deal, just thought I should post the issue here since the crashlog doesn't explicitly mention Immersive Integration. I'm probably not going to be the only person to try it and report it. :stuck_out_tongue: 

Always good to have an issue open already.
