### ISSUE TITLE
Crash with Forestry

### ISSUE THREAD

**Issue by AlexPlus117** [UnwrittenFun/ImmersiveIntegration#45]
Hi, after updating IE and II to 0.6, my client crashes. Here's the report: http://pastebin.com/qruYZqMD

**Comment by jamesbirtles** [comment]
Not my issue, I think it is to do with outdated forestry or something, @BluSunrize would know

**Comment by jamesbirtles** [comment]
See:
- BluSunrize/ImmersiveEngineering#571
- BluSunrize/ImmersiveEngineering#561
- BluSunrize/ImmersiveEngineering#559

**Comment by AlexPlus117** [comment]
Yes, I've already spoken with him and he says that Forestry 3 is not supported anymore.
