### ISSUE TITLE
Crash with place ME Dense Transformer

### ISSUE THREAD

**Issue by Tsyklop** [UnwrittenFun/ImmersiveIntegration#46]
I place ME Dense Transformer and - crash.
log: http://pastebin.com/NYmgRvXB

IE 0.6. II 0.6. AE2 rv3 - alpha

**Comment by jamesbirtles** [comment]
I do not support ae2 rv3.
Taken from ae's website "Rv3 Alpha is not compatible with any AE2 addons, do not request add-on authors or other mod developers to support these builds."

**Comment by Tsyklop** [comment]
@UnwrittenFun ae2stuff works with AE2 rv3...

**Comment by jamesbirtles** [comment]
And II won't until it is the recommended version.

**Comment by Tsyklop** [comment]
@UnwrittenFun huh...okey...

**Comment by jamesbirtles** [comment]
I can't support both so I'm going to support stable over alpha
