### ISSUE TITLE
Transformers on post extenders

### ISSUE THREAD

**Issue by M0rt1mer** [UnwrittenFun/ImmersiveIntegration#48]
Transformer can't be attached to wooden post extension the same way it can be to wooden post

**Comment by jamesbirtles** [comment]
As of right now, this isn't particularly easy to do, I will talk to Blu though and see if we can work something out.

**Comment by jamesbirtles** [comment]
I've submitted a PR to IE (BluSunrize/ImmersiveEngineering#664) to make this possible, we'll see how it goes.
