### ISSUE TITLE
Appeng insta crash when placing ME wire connector in world (both kinds)

### ISSUE THREAD

**Issue by Zedrimar** [UnwrittenFun/ImmersiveIntegration#49]
So yeah, if you place the thing(s) in the world you just crash

Crash: http://paste.ubuntu.com/13297096/

**Comment by OneEyeMaker** [comment]
Immersive Integration works only with STABLE versions of AE2! (=use AE2-rv2). 

Creating addon for unstable mod is stupid idea, because this unstable (alpha) version of mod can contain many bugs and API can be changed very quickly in further versions.

And so, use only STABLE versions of mods.

**Comment by Zedrimar** [comment]
sorry my bad :/

**Comment by Zedrimar** [comment]
Wrote this in a hurry and forgot I had the alpha version! XD else I would have not even reported this
