### ISSUE TITLE
Industrial Coke Oven shows negative fluid values

### ISSUE THREAD

**Issue by angelnc1989** [UnwrittenFun/ImmersiveIntegration#50]
When the Industrial Coke Ovens internal fluid tank is full it somehow shows negative values in the GUI,  WAILA however shows the correct 64000/64000mb.
http://imgur.com/a/0r82c

**Comment by jamesbirtles** [comment]
That's... interesting
I'll try to reproduce

**Comment by 2bithacker** [comment]
I'm seeing this as well, and I think it may cause the ICO to keep processing input even though it isn't making any more liquid. Maybe that's intentional, but normal Coke Ovens halt if their tanks fill. I'll see if I can confirm the behavior and document it a bit.

**Comment by jamesbirtles** [comment]
It is intended that it will keep processing even if the liquid cannot fit

**Comment by compwiz1548** [comment]
I've noticed this as well, however I'm seeing it when using a TC drain to remove creosote. The tank goes negative and it just keeps pouring, effectively giving infinite creosote. This is using FTB Infinity 2.2.2.

**Comment by defakto** [comment]
Also had the same issue today with Immersive integration 0.6.6, FTB infinity 2.3.3

Just got it to roll over again while watching.   I think it's an integer issue for the value you're storing in the creosote tank.

It appeared that the roll over happened around as I crossed over 32,000 creosote in the tank.  You are probably using a signed, 16 bit integer which tops out at 32,767.  Once you cross that value, you're rolling over to the negative.

You just need a check to prevent overflowing your integer, both signed or unsigned.  Seems to be just a GUI error, as putting bottles in outputs what you would expect.

Series of shots showing:

Early Run:
![2016-02-28_12 05 02](https://cloud.githubusercontent.com/assets/2061658/13380925/cb2fb800-de13-11e5-9e19-634ffd4d5101.png)

Near 32,767
![2016-02-28_12 05 42](https://cloud.githubusercontent.com/assets/2061658/13380926/cc86344a-de13-11e5-864b-461ca4c957fa.png)

Just passed over 32,767
![2016-02-28_12 06 24](https://cloud.githubusercontent.com/assets/2061658/13380927/cea11736-de13-11e5-9165-ab9d26383817.png)

**Comment by jamesbirtles** [comment]
TIL `sendProgressBarUpdate` sends a short in the packet instead of the int it takes :flushed:
