### ISSUE TITLE
ME Dense Transformer render problem

### ISSUE THREAD

**Issue by SirFlip** [UnwrittenFun/ImmersiveIntegration#51]
Hi,
I am getting a lot of lag with your ME Dense Transformer. See Opis Log.
It would be kind of you if you can improve the render time.
And maybe look into this issue.
![me-transformer](https://cloud.githubusercontent.com/assets/6735323/11407164/3c9ec484-93b1-11e5-93fe-8fc5352a22a4.PNG)

**Comment by jamesbirtles** [comment]
Err that is probably because prior to IE 0.6.0 wire connectors did wire rendering every render tick. I had  code in the transformer to do this just like wire connectors, however it seems I don't need that now.

**Comment by jamesbirtles** [comment]
Let me know in the next release if there are still issues, coke oven might be better as well with some changes I am hoping to do

**Comment by SirFlip** [comment]
Just want to let you know that it's mutch better now.

**Comment by jamesbirtles** [comment]
That is great to hear thanks!
