### ISSUE TITLE
Industrial Coke Oven render causing overhead

### ISSUE THREAD

**Issue by XFactHD** [UnwrittenFun/ImmersiveIntegration#54]
As soon as the multiblock gets formed, opis shows a tick time of about 1500 ms and kills my fps although I am using a GeForce GTX 760.

**Comment by jamesbirtles** [comment]
It shouldn't be that bad, it is just rendering a model as any other mod would, however I am planning on improving it further, see last comment on #51

**Comment by XFactHD** [comment]
I have seen that issue already but didn't think of it as I wrote this.
