### ISSUE TITLE
Client Crash with newest IE and II Version

### ISSUE THREAD

**Issue by ghost** [UnwrittenFun/ImmersiveIntegration#57]
http://pastebin.com/cssb6F65

Forge: 10.13.4.1558, IE: 0.6.3, II: 0.6.4

**Comment by BluSunrize** [comment]
Yeah sorry about that @UnwrittenFun, but that nixie font had to be made optional^^

**Comment by jamesbirtles** [comment]
Dammit Blu

**Comment by jamesbirtles** [comment]
Fixed in 0.6.5
http://minecraft.curseforge.com/projects/immersive-integration/files/2270022
