### ISSUE TITLE
Dense ME Wires don't transfer in loaded RFTools dim once you leave

### ISSUE THREAD

**Issue by Alaberti** [UnwrittenFun/ImmersiveIntegration#59]
Version: Immersive Integration 0.6.5, Immersive Engineering 0.6.4, Forge 1558

Background: I run a dedicated server where I have a RFTools void dimension where I'm running Dense ME wire between various outposts. I have all the wires chunk loaded with World Anchors and the dimension has a chickenchunks loader away from all the wires in order to load the dim on server startup.

Issue: Whenever I leave the dimension and reenter the dimension, regardless of the method, the wires no long extend the ME system. It's like they unload and don't reconnect. Help please?

Edit: Included versions.

**Comment by Alaberti** [comment]
As mentioned in #60, even on 0.6.6, this issue seems to to persist.I have a chickenchunks loader to keep the dim from unloading. I've also noticed [immersiveintegration]: null popping up in the server console from time to time.

To reiterate the issue, it seems as though leaving the dim and returning causes the me wire/connectors/transformers to completely disconnect from my ME system (linked to the transformer via a dense me cable). The run I'm using itself is about 15 connectors long. Attached is a sample of the run from the main facility to the outermost transformer.

![2015-12-18_15 58 05](https://cloud.githubusercontent.com/assets/10929796/11899590/35d60116-a5a0-11e5-86c4-da5cdaecd6ef.png)
![2015-12-18_15 58 20](https://cloud.githubusercontent.com/assets/10929796/11899591/35d7d1f8-a5a0-11e5-956e-e05ce8e0033f.png)
![2015-12-18_15 58 24](https://cloud.githubusercontent.com/assets/10929796/11899592/35dacfd4-a5a0-11e5-9cfc-faee56034254.png)

**Comment by jamesbirtles** [comment]
Hmm I had hoped this was the same issue as #60, obviously not though. Time for me to learn how to rftools I guess..

**Comment by Alaberti** [comment]
I originally thought it was related to the dim unloading, but as it isn't unloading when I leave it, I'm not sure what additional information I can give you. Maybe @McJty can help?
