### ISSUE TITLE
ME Wire not Active after Restart

### ISSUE THREAD

**Issue by SirFlip** [UnwrittenFun/ImmersiveIntegration#60]
Hi,
I'm having an similar issue like #59, but also in normal worlds.
On large distances the ME wire (both dense and normal) weren't connecting the ME System. They are still there and you have to cut and replace the wires to fix it.
Happens on server restarts or leave join in single player.
Short distances are fine.
Happend for me after upgade from 0.6.1 to 0.6.5

**Comment by SirFlip** [comment]
Testet a little bit more and found out that it seams to happen when you have 2 or more wire connectors in between.

**Comment by Alaberti** [comment]
I upgraded to 0.6.6; however, I am still experiencing the same issue even after replacing all wire connectors and wires. @SirFlip, has the issue gone away for you?

**Comment by SirFlip** [comment]
Yes for me it's working now after the Update

**Comment by Alaberti** [comment]
Looks like it's more related specifically to #59 then. I continue reporting there.
