### ISSUE TITLE
Server console spamming immersiveintegration]: null 

### ISSUE THREAD

**Issue by Alaberti** [UnwrittenFun/ImmersiveIntegration#62]
Just like it says, I've been seeing it for awhile but I don't know why it's happening?

Also, happy holidays! Hope to hear from you AFTER the winter solstice!

**Comment by Alaberti** [comment]
Hello! Any ideas about this problem?

**Comment by jamesbirtles** [comment]
It happens when connecting ae wires, either manually or on chunk/world load for instance. Technically there should be a message but I guess AE don't send one down. 'Meh'

**Comment by Alaberti** [comment]
Fair enough. Is it possible to make this a silent log then?
