### ISSUE TITLE
Crash loop upon placing an Item Robin

### ISSUE THREAD

**Issue by Samario1** [UnwrittenFun/ImmersiveIntegration#65]
When an Item Robin is placed, it apparently loses its name for that player, and from then on any attempt to display its name (looking at it with WAILA, mousing over it as a tooltip, the name display on selecting it) crashes the client.
[Openeye crash report here](http://openeye.openmods.info/crashes/5854c7d8c2bdcd9ebc8ce8a224b71739)

**Comment by jamesbirtles** [comment]
Update to the latest II and come back to me.

**Comment by Samario1** [comment]
Crash report was generated with version 0.6.6, which (as far as I can tell) is the latest version.

**Comment by jamesbirtles** [comment]
According to the report it was using "immersiveintegration-0.6.3.jar"
