### ISSUE TITLE
Wooden Post Extensions Removed?

### ISSUE THREAD

**Issue by Invalidnull** [UnwrittenFun/ImmersiveIntegration#67]
I just updated the FTB Infinity modpack to version 2.3.5 which has version 0.6.6 of Immersive Integration and I cannot find the Wooden Post Extension. Has it been removed?

Edit: Disregard, I found the Extendable Wooden Post that uses Treated Wood Fence (I just discovered that there is an in-game manual as well). I also realized the you have to shift click to attach things to the arms, a little annoying when flying but understandable when climbing the pole as you will be holding shift anyway to hold on.

This issue can be closed.
Thanks for the wonderful mod.

**Comment by jamesbirtles** [comment]
Yeah the shift thing is my derp, it is fixed in dev, just needs a release :)
