### ISSUE TITLE
Industrial Coke Oven Randomly Producing More Coal Coke?

### ISSUE THREAD

**Issue by GeoTerra** [UnwrittenFun/ImmersiveIntegration#68]
Using Immersive Integration v0.6.6 and I managed to build the Industrial Coke Oven, which, might I add, is no mean feat due to the diagram from the book being rather unclear as to the "inside" of the structure, but that's another thing entirely.

I put in a stack of Coal Blocks to process (manually), so there were 16 blocks per slot. I had Creosote being pulled out via an XU Fluid Node. Went off to tackle some infrastructure issues I was having at them time. When I came back, I noticed I had gotten back more coal coke than the coal I had put in. I have since lost that world, but I believe the return was a stack plus something to the tune of 10 extra blocks.

I would like to confirm that this is or is not a bug in the ICO as I thought it was a bit odd in nature.

Thank you for your time.

**Comment by XFactHD** [comment]
This is intended behaviour. I think it is even written in the manual.

**Comment by jamesbirtles** [comment]
Intended, in terms of the book issue, I might consider adding a texture to the top of the blocks to make it easy to see which type they are
