### ISSUE TITLE
Creative multiblock placer.

### ISSUE THREAD

**Issue by Claycorp** [UnwrittenFun/ImmersiveIntegration#69]
As Blu is against creating a tool for people to place multiblocks I thought it would be a good idea to ask here.

The idea is simple. Right click with special creative only item and it spawns the appropriate multiblock facing you. Makes life easier for Server ops, pack devs and testing whatever.
If this doesn't fit the idea of the mod then oh well. Was worth a shot.

**Comment by jamesbirtles** [comment]
Sorry, I don't want to go behind Blu's back and add an item he is against.

**Comment by K-4U** [comment]
"It's against the wishes of original dev, so i'm going to ask somebody else"
Wow, way to be a dick mate..

**Comment by Claycorp** [comment]
He purely doesn't want to do it because he thinks people will complain... It doesn't affect the play of the mod at all. I don't see how that's "being a dick" when someone asks for a tool to make things quicker.

**Comment by XFactHD** [comment]
He is not only against it because people would complain but also because of "Minecraft being Minecraft". The tool would need to place all blocks at once (can create lag), notify all blocks of the placement (update the blocks; can create even more lag) and finally imitate a hammer to form the multiblock (because otherwise people would complain; can be a bit tricky).

**Comment by Claycorp** [comment]
Yeah it wouldn't be as laggy as you make it out to be. It would be negligible unless you are spamming the thing. You totally can set it to replace only certain blocks so the whole block replacement stuff is just as moot of a point.

But hey. If people want to make such a huge deal at how bad this would be lets do it! Yaknow because asking for tools to help improve experiences with dealing with the mod is such a slanderous thing.
