### ISSUE TITLE
[AE2] Allow Metal Press to use Inscriber Press

### ISSUE THREAD

**Issue by Shadows-of-Fire** [UnwrittenFun/ImmersiveIntegration#77]
A press is a press, and it it would make sense to allow the metal press to accept these items as presses unless its a hardcoded list.  It would allow for much more interesting AE2 inscriber setups, moving the inscriber only to the last step of the process, since the Metal Press doesn't function in that manner.

**Comment by XFactHD** [comment]
So you want the raw circuits to be made in the metal press and the chips to be made in the inscriber? I like this idea and it should be possible.

**Comment by Shadows-of-Fire** [comment]
I came up with the idea since I was trying to integrate mods and make the inscriber less important, and put more of a focus on multiblock parts.
