### ISSUE TITLE
[Suggestions]About Wooden Post Extension and Redstone Wire Connector's chat information

### ISSUE THREAD

**Issue by CannonFotter** [UnwrittenFun/ImmersiveIntegration#9]
When I tried IE's Wooden Post , I found that I can climb like this.
![2015-07-11_23 19 10](https://cloud.githubusercontent.com/assets/11025035/8634269/e3241a28-2824-11e5-9651-e00004a4c24a.png)

Also I tried Wooden Post Extension , but I can't do this.
Can you add the features?
Another suggestions comes form my friend bakaxyf who translated II into Chinese.
When he translate it , he found that Redstone Wire Connector's chat information is hardcoded.
He thought some people in China may not know what does it mean. So did I.
Can you add the localization for it?
Thank you very much!

**Comment by jamesbirtles** [comment]
They just added climbing the post in the latest update with the comment "made wooden posts climbable. Temporary feature, might be removed again.". If that feature stays then I will consider adding that capability.

The lack of translation for that is because I forgot to, will be in the next update :)

**Comment by jamesbirtles** [comment]
On that note, I will quickly add the ability to translate now, so either you or @bakaxyf can translate it before the next update

**Comment by bakaxyf** [comment]
#11

![image](https://cloud.githubusercontent.com/assets/10368307/8636368/198d19a0-2890-11e5-88ec-b9ffc265f86e.png)
Are "input" and "output" hardcoding too?

**Comment by jamesbirtles** [comment]
not sure how I missed that, I'll change that when I get the chance but they will use immersiveintegration.chat.input and immersiveintegration.chat.output

**Comment by bakaxyf** [comment]
eea86d76581a12e1b1798e617a9a16b9f0029540

**Comment by jamesbirtles** [comment]
Going to close this until a decision is made on if the climbing will be a long-term feature
